name: flutter_exoplayer
description: A flutter plugin to play audio files using the Java ExoPlayer library.
version: 0.5.2
author: Daniel Rachlin <daniel.rachlin@gmail.com>
homepage: https://github.com/danielR2001/flutter_exoplayer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  uuid: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
flutter:
  plugin:
    androidPackage: danielr2001.audioplayer
    pluginClass: AudioPlayerPlugin
